### ISSUE TITLE
File explorer not showing Error Message correctly

### ISSUE THREAD

**Issue by yeungalan** [tobychui/ArOZ-Online-System#10]
![image](https://user-images.githubusercontent.com/12872405/77139698-3a77e100-6a34-11ea-8111-6767cb6a4aed.png)

**Comment by tobychui** [comment]
This mostly happens when the given folder do not exists. This should be an Error of displaying error message instead of not working properly.

**Comment by tobychui** [comment]
Fixed in the latest build, will be releasing soon.
![2020-03-21_15-39-05](https://user-images.githubusercontent.com/24617523/77222109-3dd1b080-6b8b-11ea-9757-fcb1772fc09e.png)
