### ISSUE TITLE
The AOBWS auth screen confirm button cannot show in 1366x768 screen

### ISSUE THREAD

**Issue by yeungalan** [tobychui/ArOZ-Online-System#15]
![image](https://user-images.githubusercontent.com/12872405/77614091-938abd80-6ee9-11ea-8414-cf3d45b4bfe9.png)
As title

**Comment by tobychui** [comment]
1366 * 768 is the minimum supported screen size for ArOZ Online system and it should have no problem.  Tested using Firefox Responsive Design Mode. Problem cannot be reproduced.
![2020-03-27_13-40-36](https://user-images.githubusercontent.com/24617523/77725533-a9ef6100-7030-11ea-9860-238ec95f1ff9.png)

**Comment by yeungalan** [comment]
Try to use Chrome, man :)

**Comment by tobychui** [comment]
![2020-03-27_13-47-51](https://user-images.githubusercontent.com/24617523/77725887-955f9880-7031-11ea-8e69-d0e79dc90384.png)
Chrome RD mode show no different owo?

**Comment by yeungalan** [comment]
![image](https://user-images.githubusercontent.com/12872405/77726296-d796c480-6fb4-11ea-9be1-574a02d9eac1.png)
Firefox had same issues
I recommend you find a real 1366x768 machine to test it instead of just using emulator =w=

**Comment by tobychui** [comment]
100px reduction in height is made to the iframe object and will be updated following with next commit. 

![2020-03-27_13-52-32](https://user-images.githubusercontent.com/24617523/77726321-9d6c0800-7032-11ea-8da5-0480a769662a.png)
![2020-03-27_13-40-36](https://user-images.githubusercontent.com/24617523/77726340-a230bc00-7032-11ea-936a-61b322c395ef.png)



> 
> 
> ![image](https://user-images.githubusercontent.com/12872405/77726296-d796c480-6fb4-11ea-9be1-574a02d9eac1.png)
> Firefox had same issues
> I recommend you find a real 1366x768 machine to test it instead of just using emulator =w=

I don't have a machine with such low resolution ouo
