### ISSUE TITLE
Desktop icon not showing properly after changing resolution

### ISSUE THREAD

**Issue by yeungalan** [tobychui/ArOZ-Online-System#4]
![image](https://user-images.githubusercontent.com/12872405/77139380-0f40c200-6a33-11ea-816a-1be6ef1ee39b.png)

**Comment by tobychui** [comment]
For files that you manually drag and dropped, they will remain at their original location even though you have resized your screen. Currently there are no good solutions to tackle this problem. Anyone have any suggestion?

**Comment by tobychui** [comment]
This is a feature, not a bug.
