### ISSUE TITLE
The filename at Desktop was missing

### ISSUE THREAD

**Issue by yeungalan** [tobychui/ArOZ-Online-System#5]
![image](https://user-images.githubusercontent.com/12872405/77139407-2ed7ea80-6a33-11ea-902e-c1d9f796a3a5.png)

**Comment by tobychui** [comment]
Cannot reproduce. Can you share more information on what is the original filename of the .psd file? Is that UTF-8 compatible? Please also include your system information (e.g. Host OS, AOB version etc)

**Comment by yeungalan** [comment]
Original filename:  きみのなは.psd
Version Code: AOB-DEVB_v16-2-2019
Host OS: Debian 10

**Comment by yeungalan** [comment]
No fixes right now, Closing
Reopen if needed

**Comment by yeungalan** [comment]
Well this bug fixed when updated to PHP 7.4
Just note that if people had problem on encoding, try update PHP first :)
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/12872405/77396270-acb43280-6d60-11ea-8d3f-0f703be94570.png">
