### ISSUE TITLE
Icon not aligning as same position

### ISSUE THREAD

**Issue by yeungalan** [tobychui/ArOZ-Online-System#9]
![image](https://user-images.githubusercontent.com/12872405/77139661-12887d80-6a34-11ea-8460-6a823248f9a6.png)

**Comment by tobychui** [comment]
![2020-03-23_18-07-46](https://user-images.githubusercontent.com/24617523/77305623-567bcb00-6d31-11ea-8e17-85cf44c64cde.png)
Fixed in the latest build. Aligning the bottom of all shortcut icons, file icons and webapp icons.
